from __future__ import annotations

DOMAIN = "unite_evcc_bridge"

CONF_UNIT_ID = "unit_id"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_POLL_INTERVAL = "poll_interval"
CONF_MAX_CURRENT = "max_current"
CONF_FAILSAFE_CURRENT = "failsafe_current"
CONF_FAILSAFE_TIMEOUT = "failsafe_timeout"
CONF_PHASE_RECOVERY_ENABLED = "phase_recovery_enabled"
CONF_PHASE_RECOVERY_OBSERVE = "phase_recovery_observe"
CONF_PHASE_RECOVERY_DWELL = "phase_recovery_dwell"
CONF_REST_ENABLED = "rest_enabled"
CONF_REST_USERNAME = "rest_username"
CONF_REST_PASSWORD = "rest_password"

DEFAULT_PORT = 502
DEFAULT_UNIT_ID = 255
DEFAULT_POLL_INTERVAL = 10
DEFAULT_SCAN_INTERVAL = DEFAULT_POLL_INTERVAL
MIN_POLL_INTERVAL = 5
MAX_POLL_INTERVAL = 60
DEFAULT_MAX_CURRENT = 16
DEFAULT_RESUME_CURRENT = 6
DEFAULT_FAILSAFE_CURRENT_A = 6
DEFAULT_FAILSAFE_TIMEOUT_S = 30
DEFAULT_PHASE_RECOVERY_ENABLED = False
DEFAULT_PHASE_RECOVERY_OBSERVE_S = 60
DEFAULT_PHASE_RECOVERY_DWELL_S = 121
DEFAULT_REST_ENABLED = False
DEFAULT_REST_USERNAME = "admin"
REST_RESTART_COOLDOWN_S = 300
REST_TIMEOUT_S = 15
HEARTBEAT_ALIVE_VALUE = 1
